environment:
  domain: backbase.test

bb-fuel:
  platform:
    registry: https://registry-latest-usa.retail.backbase.eu
    identity: https://identity-latest-usa.retail.backbase.eu
    gateway: https://app-latest-usa.retail.backbase.eu/api
    auth: https://app-latest-usa.retail.backbase.eu/api/auth/login
    tokenconverter: https://tokenconverter-latest-usa.retail.backbase.eu
  dbs:
    accessgroup: https://accessgroup-latest-usa.retail.backbase.eu
    accounts: http://account.${environment.name}.${environment.domain}/service-api
    approvals: https://approvals-latest-usa.retail.backbase.eu/integration-api
    arrangements: https://arrangements-latest-usa.retail.backbase.eu/client-api
    billpay: http://billpayprovidermock.${environment.name}.${environment.domain}/client-api
    contactmanager: https://contacts-latest-usa.retail.backbase.eu/integration-api
    legalentity: https://legalentity-latest-usa.retail.backbase.eu
    transactions: https://transactions-latest-usa.retail.backbase.eu
    user: https://user-latest-usa.retail.backbase.eu/client-api
  dbs-service-names:
    accessgroup: accessgroup-presentation-service
    actions: actionrecipes-presentation-service
    arrangements: product-summary-presentation-service
    billpay: billpay-presentation-service
    legalentity: legalentity-presentation-service
    limits: limits-presentation-service
    messages: messages-service
    notifications: notifications-service
    payments: payment-order-service
    pfm: categories-management-presentation-service
    user: user-presentation-service
    products: product-summary-presentation-service